name: DeathSwap
version: '${version}'
main: com.mohammadfaizan.deathSwap.DeathSwap
api-version: '26.2'
commands:
  deathswap:
    description: Start a DeathSwap game
    usage: /<command> [ start | stop | leave | stats ]
    aliases: [ds]
